### ISSUE TITLE
Using with dRNA-Seq Data

### ISSUE THREAD

**Issue by a-slide** [nanoporetech/isONclust2#2]
Hi @bsipos 
It looks like a fab option for de novo clustering and transcriptome assembly.
Could you clarify if it is also possible to use dRNA-Seq datasets ?
If so which parameters would you recommend to use for a first try ? 
Thanks
Ad

**Comment by bsipos** [comment]
Did not test it however, it should work on direct RNA with default parameters (might be slower though). The performance of clustering will be probably decreased as dRNA reads are not necessarily fully sequenced.

**Comment by a-slide** [comment]
OK thanks

**Comment by anshulbudhraja** [comment]
Hi @a-slide and @SomaG-PSN ! wondering if it worked on dRNA datasets for either of you?

**Comment by ksahlin** [comment]
As @bsipos replied it works. We just haven't measured the accuracy on dRNA datasets. You can also run [isONclust](https://github.com/ksahlin/isONclust) with your data and head over there to post any issues/results as I am maintaining that repository.
