### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by Kirovez** [nanoporetech/isONclust2#4]
Hi!
I have run the following command with Direct RNA sequencing reads: 
`isONclust2 sort -F 2  -v -o DRS_reads.fq`

And I got the following output with the error occurred:
`isONclust2 version: v2.3-e9da596
Batches output directory: sorted
Minimum batch size: 50000 kilobases
Kmer size: 11
Window size: 15
Consensus period: 500
Minimum cluster size for consensus: 50
Maximum cluster size for consensus: -150
Minimum average quality: 7
Minimum shared minimizers: 5
Minimum fraction of top minimizer hit: 0.8
Mapping threshold: 0.65
Alignment threshold: 0.2
Minimum probability no hit: 0.1
Minimum cluster size in left batches: 2
Debug output: off
Warning: reusing existing output directory: sorted
Warning: reusing existing output directory: sorted/batches
Parsed 380000 sequences.
Finished sorting sequences.
Sorted sequences written to: sorted/sorted_reads.fastq
Scores written to: sorted/scores.tsv
Preparing batches:
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)`

**Comment by lucapandolfini** [comment]
I experienced the same problem. You should try converting U to T in the fastq file, in my case it solved the issue.
Thanks to @tleonardi
