### ISSUE TITLE
What is the impact of Different order of merging cer files?

### ISSUE THREAD

**Issue by ErisonChen** [nanoporetech/isONclust2#5]
hi, there,
     The  isONclust2  example code is listed below.

```
# sort reads and write out batches:
isONclust2 sort -B 50000 -v ens500.fq

# initial clustering of individual batches:
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_0.cer -o b0.cer
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_1.cer -o b1.cer
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_2.cer -o b2.cer
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_3.cer -o b3.cer
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_4.cer -o b4.cer
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_5.cer -o b5.cer

# merge cluster batches:
isONclust2 cluster -v -l b0.cer           -r b1.cer -o b_0_1.cer
isONclust2 cluster -v -l b_0_1.cer        -r b2.cer -o b_0_1_2.cer
isONclust2 cluster -v -l b_0_1_2.cer      -r b3.cer -o b_0_1_2_3.cer
isONclust2 cluster -v -l b_0_1_2_3.cer    -r b4.cer -o b_0_1_2_3_4.cer
isONclust2 cluster -v -l b_0_1_2_3_4.cer  -r b5.cer -o b_0_1_2_3_4_5.cer

# dump final results:
isONclust2 dump -v -i sorted/sorted_reads_idx.cer -o results b_0_1_2_3_4_5.cer
```

I have a test  with the `merge` step .
```
#Binary merge .
isONclust2 cluster -v -l b0.cer   -r b1.cer -o b_0_1.cer
isONclust2 cluster -v -l b2.cer   -r b3.cer -o b_2_3.cer
isONclust2 cluster -v -l b4.cer   -r b5.cer -o b_4_5.cer

isONclust2 cluster -v -l b_0_1.cer   -r b_2_3.cer -o b_0_1_2_3.cer

isONclust2 cluster -v -l b_0_1_2_3.cer  -r b_4_5.cer -o b_0_1_2_3_4_5.cer

```

By this way ,we  could decrease the memory cost   of about 300+ cer files' merge step.

But the result  seems not be the same with the example way.

>Below infos come from clusters_info.tsv file.

 Type | SeqNumber | ClusterNumber
---|---|---
rawONTfastq | 8604779 | 0
ExampleWay | 8604779 | 48346
BinaryTestWay | 8380306 | 13571

The clusters_info.tsv's comparison listed below.

ExampleClusterID | ExampleSize | BinaryClusterId | BinarySize
---|---|---|---
0 | 1574207 | 0 | 2049062
1 | 305805 | 1 | 292054
2 | 190015 | 2 | 281066
3 | 169258 | 3 | 274773
4 | 143181 | 4 | 235370
5 | 120562 | 5 | 199694
6 | 112505 | 6 | 197687
7 | 96978 | 7 | 171023
8 | 90645 | 8 | 138774
9 | 86133 | 9 | 109343
10 | 80531 | 10 | 103364
||.|
||.|
||.|
13565 | 8 | 13565 | 1
13566 | 8 | 13566 | 1
13567 | 8 | 13567 | 1
13568 | 8 | 13568 | 1
13569 | 8 | 13569 | 1
13570 | 8 | 13570 | 1
13571 | 8 | 13571 | 1
13572 | 8 | 
13573 | 8 | 
13574 | 8 | 
13575 | 8 | 
13576 | 8 | 
13577 | 8 | 
||.|
||.|
||.|
48341 | 1 | 
48342 | 1 | 
48343 | 1 | 
48344 | 1 | 
48345 | 1 | 
48346 | 1 | 

Could you help us find out how this happened . Or Give a certain answer of Does this test work fine.
Thanks a lot .

**Comment by bsipos** [comment]
The test looks fine, however, I strongly recommend that you use isONclust2 through the snakemake pipeline [pipeline-nanopore-denovo-isoforms](https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms) and not as a standalone tool. The pipeline merges the batches along a binary tree and also allows the parallelization of the analysis on SGE/UGE clusters.
